export enum CodeTarget {
    Clojure = "Clojure",
    CSharp = "C#",
    Curl = "curl",
    Dart = "Dart",
    Elixir = "Elixir",
    Go = "Go",
    Java = "Java",
    JavaScript = "JavaScript",
    Kotlin = "Kotlin",
    NodeHTTP = "Node (HTTP)",
    NodeAxios = "Node (Axios)",
    NodeFetch = "Node (Fetch)",
    ObjectiveC = "Objective-C",
    PHP = "PHP",
    PHPGuzzle = "PHP (Guzzle)",
    PHPRequests = "PHP (Requests)",
    Python = "Python",
    PythonRequests = "Python (Requests)",
    Ruby = "Ruby",
    Rust = "Rust",
    Swift = "Swift",
    Wget = "Wget",
}
